server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /account

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    dialect: ${SPRING_DATASOURCE_DIALECT}

  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}
    database: ${SPRING_JPA_DATABASE}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}

cors:
  allow:
    origins: ${CORS_ALLOWED_ORIGINS}

github:
  login-url: ${GITHUB_LOGIN_URL}
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: ${GITHUB_REDIRECT_URI}
  token-request-uri: ${GITHUB_TOKEN_REQUEST_URI}
  user-info-request-uri: ${GITHUB_USER_INFO_REQUEST_URI}

kakao:
  login-url: ${KAKAO_LOGIN_URL}
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-request-uri: ${KAKAO_TOKEN_REQUEST_URI}
  user-info-request-uri: ${KAKAO_USER_INFO_REQUEST_URI}

frontend:
  authentication:
    origins: ${FRONTEND_AUTHENTICATION_ORIGINS}





springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method

hr:
  service:
    url: http://localhost:8003

---

spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

